apiVersion: v1
kind: Service
metadata:
  name: service-2048
  labels:
    app: "game-2048"      
    version: "1"    
spec:
  selector:
    app: "game-2048"      
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP