grafana:
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      serve_from_sub_path: true
    auth.anonymous:
      enabled: true
      org_role: Admin
prometheus:
  prometheusSpec:
    routePrefix: "/prometheus/"